### ISSUE TITLE
Table cell text wrapping for long header names is causing spaces to appear

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-cloud-files#12]
Looking at output on both Chrome and Firefox, there's a spacing problem with the table cells that have headers that have to be wrapped within a cell. 

Output: 
http://staging.developer.rackspace.com/docs-cloud-files/#cors-headers-for-objects
shows `Access-Control-Allo w-Origin`.

Source:
https://github.com/rackerlabs/docs-cloud-files/blob/6008034ccc9fa8d38d6477a431821c9e84a0c97d/rst/dev-guide/public-access-to-your-cloud-files-account/cors.rst

If a user tries to copy/paste that header the space will come with it. Let's try to remove that space if possible. For example:

```
+-----------------------+----------------------------------------------------+
| ``Access-Control-Allo | Specifies the origins that are allowed to make     |
| w-Origin``            | cross-origin requests, separated by a space when   |
|                       | there are multiple values.                         |
+-----------------------+----------------------------------------------------+
```

should be revised to:

```
+-------------------------+---------------------------------------------------+
| ``Access-Control-Allow-  | Specifies the origins that are allowed to make   |
| Origin``                 | cross-origin requests, separated by a space when |
|                          | there are multiple values.                       |
+--------------------------+--------------------------------------------------+

```

**Comment by cyrichardson** [comment]
@meker12 Should I hand edit the tables to make the column larger to take care of this?

**Comment by meker12** [comment]
One thing to try to fix this is to use the "/"  where the content breaks to another line.  Not sure if that will fix it in the UX or not.  

You can see the use of / in the nested parameter markup in the RST files  (check https://github.com/rackerlabs/docs-cloud-servers == lots of nesting there.)

**Comment by cyrichardson** [comment]
Made an update I want to push to staging and see if this improves things.

**Comment by cyrichardson** [comment]
I ended up just extending the table column to the length of the longest parameter. All fixed now.
