### ISSUE TITLE
Examples not coming to RST cleanly

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-cloud-files#14]
Looking at https://github.com/rackerlabs/docs-cloud-files/blob/6008034ccc9fa8d38d6477a431821c9e84a0c97d/rst/dev-guide/storage-api-operations/methods/get-show-container-details-and-list-objects-v1-account-container.rst 
and 
https://github.com/rackerlabs/docs-cloud-files/blob/7569ab3271866919fbfbce02d38ddb10c611b955/src/wadl/rax-cloudFiles-api-v1-rst.wadl

and http://staging.developer.rackspace.com/docs-cloud-files/#show-container-details-and-list-objects

I see that the WADL has for example reddelicious on a line by itself, but then the RST example does not have the correct hard return under "Controlling a Large List of Objects" so you'll probably need to figure out the formatting problem there (or fix it in the RST).

**Comment by cyrichardson** [comment]
Hand edited the rst to fix this.

**Comment by cyrichardson** [comment]
Made the same type of changs for Show account details.
