### ISSUE TITLE
RST source missing link 

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-cloud-files#15]
Missing link in http://staging.developer.rackspace.com/docs-cloud-files/#create-or-update-container-metadata 

Also I'm not sure about the spacing going on there, so take a look. :eyes: :)

<img width="982" alt="screen shot 2015-09-25 at 5 07 41 pm" src="https://cloud.githubusercontent.com/assets/501981/10113249/ffdaf90c-63a7-11e5-91d8-697f504b5a32.png">

**Comment by cyrichardson** [comment]
Corrected missing link. Reformatted other by using code tag. Made similar changes using code tags in Create or update object metadata.
