### ISSUE TITLE
Account to account copy: should it be PUT or POST? 3 or back to 1?

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-cloud-files#16]
Not sure if this is the intent, but the text says PUT command but the example has a POST:

http://staging.developer.rackspace.com/docs-cloud-files/#account-to-account-copy

Then based on the formatting I'm not sure if the numbered list is a continuation of the copy above or if it's meant to be its own list and should start over at 1? Here's a screenshot in case it helps to see in context. 

<img width="1020" alt="screen shot 2015-09-25 at 5 14 37 pm" src="https://cloud.githubusercontent.com/assets/501981/10113358/29b7b962-63a9-11e5-8d1c-cdb0f4a643a9.png">

**Comment by cyrichardson** [comment]
For PUT command steps,  you are correct that the steps there should be 1 and 2 (not 3 and 4). You start over, but you start with the POST command in step 1 and then do a PUT command in step 2. 

All corrected.
