### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-files#20]
See the markup and comments in the attached Word doc for my suggested edits for the release notes. Please let me know if you have any questions. Thanks!

[Cloud Files Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-files/files/30478/Cloud.Files.Release.Notes_editsKH.docx)

**Comment by cyrichardson** [comment]
Edits applied and published.
