### ISSUE TITLE
Example needs testing

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-cloud-files#36]
A customer reported that this example does not work, could you test it? Perhaps they took it out of context but as it was reported, I want to make sure we test. 

curl -i -X PUT $API_ENDPOINT/v1/$TENANT_ID/yourContainerName/yourObjectName \
-H "X-Auth-Token: $AUTH_TOKEN" \
-H "Content-Type: image/jpeg" \
-H "Content-Length: 0"

Link: https://developer.rackspace.com/docs/cloud-files/v1/developer-guide/#uploading-an-object

**Comment by cyrichardson** [comment]
@annegentle : Checkin on this.

**Comment by cyrichardson** [comment]
@annegentle: Testing shows example does work, but I will update to say that you should put in an appropriate Content-Length and Content-Type for your object as noted in Jamie's emailed response to customer. Results below: 

Create container curl example and result:
$ curl -i -X PUT https://storage101.dfw1.clouddrive.com/v1/MossoCloudFS_0672d7fa-9f85-4a81-a3ab-adb66a880321/testContainer -H "X-Auth-Token: $AUTH_TOKEN"

HTTP/1.1 201 Created
Content-Length: 0
Content-Type: text/html; charset=UTF-8
X-Trans-Id: tx858f693aeb5d420ea43da-00568d3c5cdfw1
Date: Wed, 06 Jan 2016 16:10:04 GMT

Upload object curl example and result:
$ curl -i -X PUT https://storage101.dfw1.clouddrive.com/v1/MossoCloudFS_0672d7fa-9f85-4a81-a3ab-adb66a880321/testContainer/testObject -H "X-Auth-Token: $AUTH_TOKEN" -H "Content-Length: 0" -H "Content-Type: image/jpeg"

HTTP/1.1 201 Created
Last-Modified: Wed, 06 Jan 2016 16:24:01 GMT
Content-Length: 0
Etag: d41d8cd98f00b204e9800998ecf8427e
Content-Type: text/html; charset=UTF-8
X-Trans-Id: txce5dc394eea940a08a672-00568d3fa0dfw1
Date: Wed, 06 Jan 2016 16:24:00 GMT

**Comment by cyrichardson** [comment]
Just got this comment from support about Content-Length via IRC channel:

10:26 SCO_JohnH: typically, it should be noted that by default curl will set the content-length correctly without it being specifically set so for that example, it would be okay to omit the content-length altogether
