### ISSUE TITLE
Doc structure is non-standard

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-cloud-files#38]
the current standard doc structure has top level dir with your product name.  within that is (at least) a dir api-docs.  Under that live all the RST files and dirs like conf.py, developerguide.rst and so on.  Cloud Files has the old structure with rst/dev-guide.

Also the methods are not in one methods dir and there are two separate index files for operations, rather than one in the api-operations directory.

**Comment by cyrichardson** [comment]
Corrected with PR #40 and #41.
