### ISSUE TITLE
No 'Expand All' Option

### ISSUE THREAD

**Issue by aziouk** [rackerlabs/docs-cloud-files#68]
Hey Racker,

I've noticed that recently the API docs format has been updated. Now the sections are condensed into expandable menu's, it's much harder to get an overview, when looking for something specific, without an expand all button.

I noticed there is no expand all button, I believe this affects all docs , not just cloud files. From a usability perspective it would be really neat to have this feature to make it easier for rackers and non rackers searching the API docs.

Cheers &

Best wishes,
Adam

**Comment by catlook** [comment]
Aziouk,

Thanks for sharing your thoughts on our new collapsible format! You’re right, it affects all the docs.  We’re collecting feedback and considering the options to move forward.  Stay tuned :)

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
DevDocs on Developer Experience Team
Office: (210) 312-8193   Cell: (210) 364-1060
cat.lookabaugh@rackspace.com

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by aziouk** [comment]
Hi Guys,

Sorry to re-open this again, but I think it's still important. 

Thank you for responding to this issue, I'm not sure if you are planning to fix this still? It looks like you've added it to milestone 6, but still I find the API docs pretty much impossible to use. Perhaps it's just me that has this experience, but compared to the way API DOCS were previously, where it listed the whole content on a single page, it is now taking me literally 10x + longer to find something, since I can't use ctrl + f to find the section. This is a big thing for documentation, if it is not searchable. It also takes me longer to find the specific API section, because you've changed that too, now.

We provide API support in Managed Infrastructure, so this is very much our bread and butter, we a good proportion of our customers asking for API support. So, we probably use the docs as much as our customers.

I still feel this is a really critical usability issue, and actually, would it be that difficult to resolve the problem I'm experiencing? Please would you be so kind to look into this again? This seems like an important thing that deserves more attention,

I feel that the customer would gain greatly from usability, as would other fellow rackers.

Cheers &
Best wishes,
Adam

**Comment by lauracly** [comment]
Hi Adam,

We have an issue in our tools backlog for this type of search functionality. https://github.com/rackerlabs/docs-workstream/issues/106

We are limited in our capability to move forward with scoping/implementation on this request for two reasons:

1. We have no development resources to research how to implement this type of scoped search, or to do the actual coding.
2. We have no user research resources that can perform the necessary user validation to determine what experience we should implement for scoped search. In the past, we got user feedback that asked us to remove the scoped search, and replace it with a wider search that would provide results across our full information set.

I do appreciate you reaching out to us on this issue, and if we get any available bandwidth to address these issues I will make sure to keep you informed.

Thanks,

Laura Clymer
Senior Manager 
Rackspace Information Design and Documentation
