### ISSUE TITLE
allowed headers

### ISSUE THREAD

**Issue by buhman** [rackerlabs/docs-cloud-files#81]
Consistent with [swift#1354312](https://bugs.launchpad.net/swift/+bug/1354312), we don't document `allowed_headers`, and the impact that has on API behavior.

[get-get-object-content-and-metadata-v1-account-container-object.rst](https://github.com/rackerlabs/docs-cloud-files/blob/master/api-docs/storage-api-reference/methods/put-create-or-update-object-v1-account-container-object.rst), for example, only describes headers that have semantic relevance to (rack)swift, but doesn't describe the relationship between request headers, allowed headers, and the headers that get returned in an object response.

What would be the best way to organize this?

**Comment by buhman** [comment]
As a litmus test, [here](https://gist.github.com/buhman/32ee8583f808776f4366be0d40cb0102) is an example of valid behavior (a P3P header present in an object PUT is returned in an object GET) that is not reflected in documentation.

**Comment by cyrichardson** [comment]
@buhman Interesting bug. Maybe we should watch the OpenStack bug and follow their lead?

**Comment by buhman** [comment]
> watch the OpenStack bug and follow their lead?

I disagree. Based on the comments in that bug, their idea is slanted more towards preventing semantic/internal headers from being overridden, contrast to demonstrating the existance of that behavior.

It would be merely convenient if we could model our documentation based on upstream documentation, but I was mainly pointing out that this behavior isn't even documented upstream.

**Comment by cyrichardson** [comment]
@buhman Please feel free to provide a PR with your update to the Rackspace API docs for this. I'll be happy to review it and answer any question about the doc process that come it. You'll see a CONTRIBUTING.md file in the root of this repo if you need to check it out.

**Comment by cyrichardson** [comment]
@buhman Just checking for any update on this.

**Comment by cyrichardson** [comment]
@buhman has left the Rack.
