### ISSUE TITLE
Missing Output in Cloud Files API Docs

### ISSUE THREAD

**Issue by aziouk** [rackerlabs/docs-cloud-files#84]
Hey folks,

I was going to initiate a pull request for this one, but I'm not sure of what the information should be reflected, since some I found to be missing from the github repo as well as in the live API docs.

If we look at the creating-large-objects.rst section of the Cloud Files API docs, we can see that in the section proceeding 'Example: Upload a segment of a large object: HTTP request'. Many of the output examples are showing single letter like 'w' , or 's', this strikes me as something that is not intended.

https://github.com/rackerlabs/docs-cloud-files/blob/5451cce9e2c623015c701ac676153966608ef0ca/api-docs/use-cases/additional-storage/creating-large-objects.rst

I believe that this may have been like this for a while. Please would you be so kind to help me revert a previous version of this that had the correct output for those sections?

Cheers &
Best wishes,
Adam

**Comment by cyrichardson** [comment]
@dpgoetz Could you please take a look when you have time and let me know what changes, if any, are necessary to fix this issue? @aziouk Is correct that it has been like this for quite a while. Many thanks!

**Comment by aziouk** [comment]
Hey guys, Thanks very much for getting back so quickly!  I really appreciate it!

Cheers &
Best wishes,
Adam

**Comment by cyrichardson** [comment]
@aziouk You're welcome! 

If you know the fix before David has time to get to this issue, please just add it here. I'll be glad to create the PR, or if you'd like to do that, feel free to. I will review it. :-)

**Comment by dpgoetz** [comment]
hey- just looking over this there are some mistakes. I think those "s", "w" parts should just be removed and then we can go back and add in some decent examples. just scanning over it there is a problem here: https://github.com/rackerlabs/docs-cloud-files/blob/5451cce9e2c623015c701ac676153966608ef0ca/api-docs/use-cases/additional-storage/creating-large-objects.rst#deleting-a-large-object 

too. i don't have time to fix this right now so i guess we can make a Jira for this for one of the dev to look over? or just keep this issue open? or any pull requests will also be reviewed :) Thanks

**Comment by cyrichardson** [comment]
Just FYI, I went back to a pdf file I had from 2/13/2014, and it had the "s" and "w" examples.
For now, I will go ahead and removed those examples as @dpgoetz suggested.

**Comment by cyrichardson** [comment]
I'm going to close this issue and create 2 new ones (but reference this one) as following:
- new examples for output for creating large objects section
- fix problem in deleting a large object section
I'll assign the new issues to @dpgoetz for when he has time to come back to the. @dpgoetz if you want to create a Jira ticket for this, please feel free to do so.
