### ISSUE TITLE
Cloud files docs refer to block storage

### ISSUE THREAD

**Issue by dolph** [rackerlabs/docs-cloud-files#89]
Maybe just a copy/paste issue, but [this page](https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-interfaces/cli/cloudfiles-cli/) refers to "Cloud Block Storage" in the opening sentence, which refers to cinder (block storage), not swift (object storage).

**Comment by cyrichardson** [comment]
This doc bug is in the Core Infrastucture User Guide. @dolph I'm closing this issue here, but have opened this issue under the user guide to correct the bug: https://github.com/rackerlabs/docs-core-infra-user-guide/issues/434
