### ISSUE TITLE
Review and correct API key details

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-cloud-files#90]
From email: 3/14/2017
Apologies if I reached the incorrect team. I had a customer that referenced one of our API documentation page that had the older version on where to find the API key:
https://developer.rackspace.com/docs/cloud-files/v1/getting-started/get-credentials-include/

Reference ticket:
https://encore.rackspace.com/ticketing/account/10040922/ticket/170313-dfw-0001270

Since then the API key is now under 'My Profile & Settings'. I've clicked through the first 4 API documentation page and all of the images are referencing the old location so I'm guessing all of the API doc pages will have to be updated.

Cheers,
Angela Boulineau

**Comment by cyrichardson** [comment]
Common text - affects all API dev docs for public cloud.

**Comment by cyrichardson** [comment]
Closing this issue as it is not just a Cloud Files problem - it's all public cloud API docs. New issue is at https://github.com/rackerlabs/docs-rackspace/issues/282
