### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ui4j** [rackerlabs/docs-cloud-files#92]
Hi,

Could you please add license for this project.

Thanks

**Comment by cyrichardson** [comment]
Hello! This is the repo for issues with the Cloud Files API documentation. You might try contacting Rackspace Support if you are having a licensing issue.  
Thank you!

**Comment by cyrichardson** [comment]
Contact Support: I suggest that you contact Support at Toll Free 1-800-961-4454 or International 1-210-447-4000, or open a support ticket. One of our technicians can help you. Live chat is also available at http://www.rackspace.com/.
