### ISSUE TITLE
Support for .Net Core

### ISSUE THREAD

**Issue by naveedahmed1** [rackerlabs/docs-cloud-files#93]
Does cloud files support .Net Core 2.0?

**Comment by cyrichardson** [comment]
Hi, @naveedahmed1. Here are the docs for what is available re: .Net for Cloud Files: https://developer.rackspace.com/docs/cloud-files/quickstart/?lang=.net

**Comment by naveedahmed1** [comment]
@cyrichardson thank you for your reply. But it doesn't work on latest .Net Core 2.0

**Comment by cyrichardson** [comment]
@naveedahmed1 You're welcome. You are correct. Support for the latest .Net Core 2.0 is not available. Only what is documented at the link given in the comment above.

**Comment by naveedahmed1** [comment]
Any plans to add support for .Net Core 2.0 in near future?

**Comment by cyrichardson** [comment]
I'm sorry, @naveedahmed1. At this time, there are no current plans to add support for .Net Core 2.0.
